all:
  children:
    production:
      vars:
        ds389_repl_monitoring_lag_threshold: 20
        ds389_repl_monitoring_result_dir: '/tmp'
      hosts:
        ds389_instance_1:
          ansible_host: 192.168.2.101
          ansible_user: root
          ansible_password: Password123
          ds389_repl_monitoring_log_dir: '/var/log/dirsrv/slapd-supplier1'
        ds389_instance_2:
          ansible_host: 192.168.2.102
          ansible_user: root
          ansible_password: Password123
          ds389_repl_monitoring_log_dir: '/var/log/dirsrv/slapd-supplier2'

    staging:
      vars:
        ds389_repl_monitoring_lag_threshold: 20
        ds389_repl_monitoring_result_dir: '/tmp'
      hosts:
        ds389_instance_1:
          ansible_host: 192.168.3.101
          ansible_user: root
          ansible_password: Password123
          ds389_repl_monitoring_log_dir: '/var/log/dirsrv/slapd-supplier1'
        ds389_instance_2:
          ansible_host: 192.168.3.102
          ansible_user: root
          ansible_password: Password123
          ds389_repl_monitoring_log_dir: '/var/log/dirsrv/slapd-supplier2'
