- name: Remove merged_output.json from the controller
  ansible.builtin.file:
    path: "{{ ds389_repl_monitoring_tmp_merged_output_file_path }}"
    state: absent
  delegate_to: localhost
  run_once: true

- name: Gather analysis output files on remote machines
  ansible.builtin.find:
    paths: "{{ ds389_repl_monitoring_tmp_path }}"
    patterns: "*_analysis_output.json"
  register: files_to_remove

- name: Remove found analysis output files on remote machines
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ files_to_remove.files }}"

- name: Remove found analysis output files on controller
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ files_to_remove.files }}"
  delegate_to: localhost
