- name: Create a directory with current date
  ansible.builtin.file:
    path: "{{ ds389_replication_monitoring_result_dir }}/{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true

- name: Check if replication lag files exist
  ansible.builtin.stat:
    path: "{{ ds389_replication_monitoring_result_dir }}/{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}/replication_lag.csv"
  register: replication_lag_files
  delegate_to: localhost
  run_once: true

- name: Generate plots out of the replication lag data
  ds389_logs_plot:
    input: "{{ ds389_replication_monitoring_tmp_merged_output_file_path }}"
    csv: "{{ ds389_replication_monitoring_result_dir }}/{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}/replication_lag.csv"
    output: "{{ ds389_replication_monitoring_result_dir }}/{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}/replication_lag.png"
    replication_monitoring_threshold: "{{ ds389_replication_monitoring_lag_threshold }}"
  delegate_to: localhost
  run_once: true
  when: not replication_lag_files.stat.exists
