---
- name: Setup the environment for the ds389_replication_monitoring role
  ansible.builtin.include_tasks: setup.yml

- name: Gather CSN and etime values from access logs
  ansible.builtin.include_tasks: gather_data.yml

- name: Log instances of replication lag
  ansible.builtin.include_tasks: log_replication_lag.yml
