---
- name: Converge - Gather CSN and Merge Logs
  hosts: all
  become: true
  tasks:
    - name: Run Replication-Monitor role with merging functionality
      ansible.builtin.include_role:
        name: ds389_repl_monitoring
      vars:
        ds389_repl_monitoring_log_dir: "/tmp"
        ds389_repl_monitoring_result_dir: "/tmp"
