---
driver:
  name: docker

platforms:
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora38-ansible:latest
    name: instance1
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora38-ansible:latest
    name: instance2
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora38-ansible:latest
    name: instance3
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora38-ansible:latest
    name: instance4
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      all:
        ds389_repl_monitoring_log_dir: "/tmp"
        ds389_repl_monitoring_result_dir: "/tmp"
        ds389_repl_monitoring_lag_threshold: 1
        ds389_repl_monitoring_tmp_path: "/tmp"
        ds389_repl_monitoring_tmp_analysis_output_file_path: "{{ ds389_repl_monitoring_tmp_path }}/{{ inventory_hostname }}_analysis_output.json"
        ds389_repl_monitoring_tmp_merged_output_file_path: "{{ ds389_repl_monitoring_tmp_path }}/merged_output.json"

  # Pre-installation steps
  config_options:
    defaults:
      interpreter_python: auto_silent
    privilege_escalation:
      become: true
  lint:
    name: ansible-lint
  prepare:
    prepare_command: |
      dnf install -y python3-lib389 python3-matplotlib
