---
driver:
  name: docker

platforms:
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora38-ansible:latest
    name: instance1
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora38-ansible:latest
    name: instance2
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora38-ansible:latest
    name: instance3
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora38-ansible:latest
    name: instance4
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      all:
        ds389_replication_monitoring_log_dir: "/tmp"
        ds389_replication_monitoring_result_dir: "/tmp"
        ds389_replication_monitoring_lag_threshold: 1
        ds389_replication_monitoring_tmp_path: "/tmp"
        ds389_replication_monitoring_tmp_dslogs_script_path: "{{ ds389_replication_monitoring_tmp_path }}/dslogs.py"
        ds389_replication_monitoring_tmp_dslogs_output_file_path: "{{ ds389_replication_monitoring_tmp_path }}/{{ inventory_hostname }}_dslogs_output.json"
        ds389_replication_monitoring_tmp_merged_output_file_path: "{{ ds389_replication_monitoring_tmp_path }}/merged_output.json"
