---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Verify connectivity to all hosts
      ansible.builtin.ping:

    - name: Verify necessary packages are installed on RedHat
      when: ansible_os_family == "RedHat"
      block:
        - name: Verify necessary packages are installed
          ansible.builtin.package:
            name: "{{ item }}"
            state: present
          loop:
            - python3
            - python3-matplotlib
          register: package_status
          failed_when: package_status is failed

    - name: Verify log directory exists with correct permissions
      ansible.builtin.stat:
        path: "{{ ds389_replication_monitoring_log_dir }}"
      register: log_dir_status
      failed_when: not log_dir_status.stat.exists or log_dir_status.stat.mode != '0755'

    - name: Verify output files are correctly generated
      ansible.builtin.stat:
        path: "{{ item }}"
      register: output_file
      loop:
        - "{{ ds389_replication_monitoring_tmp_analysis_output_file_path }}"
        - "{{ ds389_replication_monitoring_result_dir }}/{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}/replication_lag.csv"
        - "{{ ds389_replication_monitoring_result_dir }}/{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}/replication_lag.png"
      failed_when: not output_file.stat.exists
      delegate_to: localhost
      run_once: true

    - name: Check content of the CSV file for expected etime value
      ansible.builtin.shell:
        cmd: "grep '0.087274515' {{ ds389_replication_monitoring_result_dir }}/{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}/replication_lag.csv"
      register: grep_result
      failed_when: grep_result.rc != 0
      delegate_to: localhost
      run_once: true

    - name: Check content of the CSV file for expected lag value
      ansible.builtin.shell:
        cmd: "grep '5.879752159118652' {{ ds389_replication_monitoring_result_dir }}/{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}/replication_lag.csv"
      register: grep_result
      failed_when: grep_result.rc != 0
      delegate_to: localhost
      run_once: true

    - name: Check that the PNG file is not empty
      ansible.builtin.stat:
        path: "{{ ds389_replication_monitoring_result_dir }}/{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}/replication_lag.png"
      register: png_file
      failed_when: png_file.stat.size == 0
      delegate_to: localhost
      run_once: true
