---
- name: Setup Environment for 389 DS Replication Monitoring
  hosts: all
  become: true

  tasks:
    - name: Test connectivity to all hosts
      ansible.builtin.ping:

    - name: Ensure necessary packages are installed on the controller
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-matplotlib
      delegate_to: localhost
      when: ansible_os_family == "RedHat"
      run_once: true

    - name: Ensure log directory exists
      ansible.builtin.file:
        path: "{{ replication_monitoring_log_dir }}"
        state: directory
        mode: '0755'
